### ISSUE TITLE
error in laghu panchaytana puja tex file

### ISSUE THREAD

**Issue by contentcone** [stotrasamhita/puja-vidhanam#1]
Hi,

There is no \begin{document} in your above file. unable to crerate a pdf

pls check

thanks

**Comment by karthikraman** [comment]
This is included in the main file. It's not intended for separate compilation. If you need separate PDFs, look here: https://github.com/stotrasamhita/puja-vidhanam/tree/master/pujas-kindle-pdf

Thanks!
